### ISSUE TITLE
Kaksi (2) XSS-haavoittuvuutta

### ISSUE THREAD

**Issue by kaikkitietokoneista** [jpkerkkanen/opinnot#2]
[Kirjautumisessa](https://opinnot.net/kokonaisuudet/tunnistus.php) on XSS-haavoittuvuus, jos syöttää käyttäjänimekseen: `'><img src="notfound" onerror="alert('XSS');"><span ='`. Myös tehtävien katselussa on XSS-haavoittuvuus, jos osoitteena on: `https://opinnot.net/kokonaisuudet/index.php?id_kokon=79 '><img src="notfound" onerror="alert('XSS');">&naytettava=tehtava`. Luku 79 on tietenkin vapaasti vaihdettavissa.

**Comment by jpkerkkanen** [comment]
Kiitos vinkistä! Pitää vähän tarkastella koodia.

**Comment by jpkerkkanen** [comment]
Nyt pitäisi olla parempi. Kiitokset! Turvallisuuden suhteen minulla on kyllä vielä paljon oppimista, mutta vähitellen..
